Update projectlive.modules
Sage-Bionetworks/projectLive_demo pull request #18
Opened 2021-02-22 15:37 UTC by andrewelamb

2021-02-22 17:49 UTC, jaybee84 commented
Will wait to merge this in after the demo scheduled for today is done ...

2021-02-22 17:58 UTC, andrewelamb commented
There were some issues with the publications module, I added one more commit.

2021-02-26 16:30 UTC, andrewelamb commented
@jaybee84 I updated projectlive modules. This has the theme concatenation issue fix, and adds the latest updates such as the study table being filterable by initiative.

2021-03-06 00:01 UTC, jaybee84 requested changes

2021-03-06 00:01 UTC, jaybee84 commented on R/app_ui.R
>          projectlive.modules::summary_snapshot_module_ui("summary_snapshot_ui_1"),
Re: theme concatenation:
I am still seeing themes joined together by `|`
<img width="1322" alt="Screen Shot 2021-03-05 at 3 56 07 PM" src="https://user-images.githubusercontent.com/17917521/110186862-5ef6d580-7dcb-11eb-8ed4-d7ede4dac74e.png">

2021-03-06 00:01 UTC, jaybee84 commented on R/app_ui.R
> +        icon = shiny::icon("chart-area")
The bottom plot is being overtaken by the legend
<img width="1329" alt="Screen Shot 2021-03-05 at 3 58 35 PM" src="https://user-images.githubusercontent.com/17917521/110187119-14c22400-7dcc-11eb-97b0-54be8bfd17ce.png">

2021-03-06 00:04 UTC, andrewelamb commented on R/app_ui.R
>          projectlive.modules::summary_snapshot_module_ui("summary_snapshot_ui_1"),
This update doesn't have that fix, it was the one done right before Julie's demo.

2021-03-06 00:05 UTC, andrewelamb commented on R/app_ui.R
> +        icon = shiny::icon("chart-area")
We could either truncate this, or we should pick something else to use as fill colors.

2021-03-06 00:06 UTC, jaybee84 commented on R/app_ui.R
>          projectlive.modules::summary_snapshot_module_ui("summary_snapshot_ui_1"),
So should we update the renv.lock file for this PR to update the projectlive.module version? or would you like to start a new PR with all the updates?

2021-03-06 00:10 UTC, andrewelamb commented on R/app_ui.R
>          projectlive.modules::summary_snapshot_module_ui("summary_snapshot_ui_1"),
Either is fine with me. The config files will need to be updated I think as well.

2021-03-06 00:11 UTC, andrewelamb commented on R/app_ui.R
>          projectlive.modules::summary_snapshot_module_ui("summary_snapshot_ui_1"),
I guess my preference would be to accept this merge request and I'll open another branch to make the latest updates.

2021-03-06 00:16 UTC, jaybee84 commented on R/app_ui.R
>          projectlive.modules::summary_snapshot_module_ui("summary_snapshot_ui_1"),
just so we (mostly me) do not get confused as to which updates have been added, would you mind starting a PR against the current `update_projectlive.modules` to add in the updates? 
Then I can merge them into this branch and then merge the updated branch into the main demo branch.

2021-03-10 06:39 UTC, merged